name: Test

on: push

permissions:
  contents: read

jobs:
  phpunit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 7.3, 7.4, 8.0, 8.1 ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3